### ISSUE TITLE
SMZ3: completion condition does not account for new goal options

### ISSUE THREAD

**Issue by Alchav** [ArchipelagoMW/Archipelago#1129]
### What task needs to be completed?

SMZ3's completion condition is still just checking for tower ascension. However, it is now possible to have a higher crystal requirement for defeating Ganon than for entering Ganon's Tower. With minimal accessibility no longer causing generation failures, I expect to see it used more, and it could easily lead to unbeatable dungeons preventing access to enough crystals to actually beat the game.

@lordlou

**Comment by Alchav** [comment]
Even without considering the new goal options, it doesn't seem like this completion condition logically requires silver arrows for the Ganon fight?

**Comment by lordlou** [comment]
Fixed with https://github.com/ArchipelagoMW/Archipelago/pull/1133.
From what I can see, silver arrows arent logically required for Ganon in vanilla SMZ3. Its considered nice to have. Although, its true that it is always reachable there but not necessarily in AP with non locations accessibility, I think its fine as it is because in a SMZ3 vanilla multiworld, that item could be far for a player.

**Comment by Alchav** [comment]
Does SMZ3 upstream even have a completion condition specified? I understand it to not have an equivalent to "minimal" accessibility, so that wouldn't be needed. Since we have that option, I think it should be ensured to be available by including it in the completion condition.

**Comment by lordlou** [comment]
Isnt the point of minimal accessibility to logically (possibly) reduce whats required to a bare minimum? Also, if we do add the rule for silver arrows, isnt it the same thing for the 2 last sword upgrades and even the 2 Tunic upgrades, as they are in that same Nice to have pool.

**Comment by Alchav** [comment]
Silverless Ganon requires a glitch though. I would not expect minimal accessibility to lead to glitches being required that otherwise would not be.
