### ISSUE TITLE
SNI: Update the included version of SNI to v0.0.85

### ISSUE THREAD

**Issue by Geemer** [ArchipelagoMW/Archipelago#1256]
### What feature would you like to see?

Please update the version of SNI that's included in the Archipelago installer to v0.0.85.
[https://github.com/alttpo/sni/releases/tag/v0.0.85](https://github.com/alttpo/sni/releases/tag/v0.0.85)

This version adds the ability to use the LUABRIDGE environment variables to set e.g. the port it uses. 
I often run into issues with Windows or other software reserving the port SNI uses by default and using the environment variables to set a port outside the range that can be reserved fixes it. 
It'll automatically fall back to the old default if the environment variables aren't set, so it won't break anything.

I've been manually changing the connector.lua to include this change for a few months now, but every Archipelago update overwrites the script, so it'd be appreciated if the newer version could just become the default.

**Comment by black-sliver** [comment]
Our new workflow will now automatically download the latest SNI release when creating the setup. This might still be out of date between versions, but it avoids forgetting to update on our end.
