### ISSUE TITLE
SC2 Client: Command History / Redo last command

### ISSUE THREAD

**Issue by lprc** [ArchipelagoMW/Archipelago#1265]
### What feature would you like to see?

It would be really nice to have the last command placed into the command line after pressing the arrow up key (just like with a regular shell) to reduce retyping. Tab-completion would be sugar on top.
I guess it'd be cool for other game's clients, too, however I only used and thus saw the SC2 client yet.

**Comment by Jarno458** [comment]
Yeah such an feature should prob be implemented to the CommenClient.py so that it works for all its childeren

**Comment by Berserker66** [comment]
There are the default hotkeys: https://kivy.org/doc/stable/api-kivy.uix.textinput.html#default-shortcuts
Unfortunately reproduce last input is not among those, so we'd need to add a new hotkey and handler for it.

**Comment by nicholassaylor** [comment]
I believe this is handled in #3236
