### ISSUE TITLE
Super Metroid: Progressive Bombs

### ISSUE THREAD

**Issue by mDuo13** [ArchipelagoMW/Archipelago#1309]
### What feature would you like to see?

Instead of 1 "Bomb" and N "Power Bomb" upgrades randomized separately, it would be neat to be able to set "Bombs" as a progressive upgrade, so there would be N+1 "Progressive Bomb" items. The first one would be plain bombs and the rest would be power bombs.

I think this could (sometimes) lead to seeds with a longer, more interesting level of progression. Perhaps more importantly, it would eliminate many of the conditions that can lead to a soft-lock in SM randomizer, where a bomb block respawns behind you and you are out of Power Bomb ammo—because, unlike most seeds (where Bombs are an afterthought) you would always have regular bombs first.

**Comment by Berserker66** [comment]
@lordlou
