### ISSUE TITLE
Output who's playing what

### ISSUE THREAD

**Issue by FelicitusNeko** [ArchipelagoMW/Archipelago#134]
Since it is possible to use weighted settings for what game is being played, and multiple games do not use some sort of data file to set up, it may therefore be possible for a player to put in a selection of games where there is currently no way of knowing what they're meant to be playing unless they look at the spoiler file. It would be useful if a proper list of who's playing what could be displayed, whether it's created through the command-line generator or on the website.

**Comment by Berserker66** [comment]
On the website the tracker should list this.

**Comment by FelicitusNeko** [comment]
The multiworld tracker? It doesn't show which game is being played, aside from LttP. At least not in the current version.

**Comment by Berserker66** [comment]
Click the slot number

**Comment by FelicitusNeko** [comment]
Ah, I see. I suppose one could infer which game is being played with that information. However, it took someone actively telling me that this feature exists for me to know that it does. It would be helpful if this information was more up-front.

**Comment by Ijwu** [comment]
I guess this is something we've never perceived as an issue due to multiworlds being pretty intimate with other players. You know what others are playing due to organizing the session with them, typically.

Is it often that you find this information lacking or otherwise an issue?

**Comment by KonoTyran** [comment]
I think the issue is lets say you roll for a random chance of Subnautica, STS, and Ror2 how are you supposed to know what game to boot up? on the patch download page it does not tell you what game your slot rolled. so maybe we should add an entry for every slot regardless of if there is a file to download or not.

**Comment by FelicitusNeko** [comment]
Exactly, KonoTyran. As for how often this happens; so far, it has yet to happen, but my rotation now includes both RoR2 and Timespinner, and as games get added, it could potentially start happening to other players as well.

**Comment by alwaysintreble** [comment]
I get around this by having name triggers so I have a different name for my slot depending on my game but I still have to check the tracker to see which game I'm actually going to be playing. So I agree that having them show up on a slot list maybe just not being a hyperlink is a good option.

**Comment by Berserker66** [comment]
The on the website part of this is now addressed with https://github.com/ArchipelagoMW/Archipelago/pull/163
