### ISSUE TITLE
WebHost: Should AlttP be removed from the multiworld tracker?

### ISSUE THREAD

**Issue by freyacodes** [ArchipelagoMW/Archipelago#1477]
I would like to suggest that AlttP gets removed from the multiworld tracker. Currently, the multiworld tracker is dominated by AlttP even when there are no AlttP worlds. I think this page would benefit from not being so bloated and allowing new columns to take up the cleared space.

I could potentially contribute a PR. Below is a quick and dirty prototype I made:
![image](https://user-images.githubusercontent.com/2582617/221037482-51774780-02fe-404c-82db-58956300c9ab.png)

New columns to be added could be things like:
* Type of game (Minecraft, Factorio, etc)
* Whether the goal has been completed :heavy_check_mark: 
* A percentage of how many of the total remaining locations belong to that world (not sure how to phrase this one in a table head)

Perhaps as a compromise, the current multitracker could be preserved as a secondary tracker, to be presented as an alternative when AlttP seeds are present.

**Comment by alwaysintreble** [comment]
@ThePhar is already working on this just hasn't had much free time.

**Comment by ScootyPuffJr1** [comment]
I'm interested in your first two bullets (game and goal completion) but I don't see the value in percent of checks done. I feel like that is duplicate info. I don't know what other information we have available, perhaps these: items received, progression items received, time since last connected. I understand that this might be a step in the right direction, so if other info becomes available after Phar's API changes, then we can just wait until then.

**Comment by Berserker66** [comment]
as was slightly eluded to before, the idea is to allow each game to have a game-specific multitracker, move LttP to that, default to a generic multitracker in mixed game multiworlds and default to game specific ones if they exist if only that game is present.

**Comment by Berserker66** [comment]
I disagree, the LttP specific code should be made generic, for other games to use too. Rather than axed without replacement.

**Comment by Berserker66** [comment]
Also we had people wanting to make multitrackers for their games, but so far they were told to hold off on that until Phar has revamped said tracker system. So by just removing LttP, you just delay the inevitable.

**Comment by LegendaryLinux** [comment]
The LttP tracker has specific image sizes, table styles, etc to keep it looking nice as the user adjusts the page size. Every MultiTracker would need the same level of effort to look good. How would a generic MultiTracker table, with an unknown number of columns and images be made to properly display?

**Comment by freyacodes** [comment]
The idea isn't to have one generic multitracker to deal with any kind of game-specific data. The idea is more to allow different multitrackers to exist. This could be especially useful in multiworlds that are centered around one or a few different types of games.

Multitrackers use aggregation. In the case of Factorio, you could have 6 different columns showing a fraction of the checks completed/total per level of science pack. In the case of Stardew, you could have columns of elevator levels, fish, friendship, etc. So number of checks is not necessarily a problem.

**Comment by LegendaryLinux** [comment]
If the consensus is to adapt the system to allow multi-trackers per game, then I'll concede. We'll need to make sure each multi-tracker looks good, though. As noted in https://github.com/ArchipelagoMW/Archipelago/pull/1478.
