### ISSUE TITLE
Bug: Logic Error in LADXR

### ISSUE THREAD

**Issue by JohnGoku** [ArchipelagoMW/Archipelago#1797]
### What happened?

I created my game with the latest version of the LA-DX Randomizer.
While playing I found Mambo's Mambo and the occarina before the power bracelet. So I was able to get to crazy Tracy, where I was able to buy her secret medicine. But as the area is surrounded by stones, I was locked in there. The ingame save teleported me back to the entrance of Tracy's House.

### What were the expected results?

Beeing not able to teleport to Tracy, without aquiring the Power Bracelt first.

### Software

Local generation

**Comment by j-imbo** [comment]
If you press A+B+Start+Select to open up the Save and Quit screen, randomizer adds an option "Return Home" for situations like this.

**Comment by JohnGoku** [comment]
Thank you. haven't paid attention to that.
