### ISSUE TITLE
Cleanup: Timespinner Typo in options

### ISSUE THREAD

**Issue by Mathx2** [ArchipelagoMW/Archipelago#2153]
### What happened?

Timespinner Options.py
For BossScaling on line 63 the last word is (Reccomended)

### What were the expected results?

the correct spelling is (Recommended)

### Software

Website

**Comment by Jarno458** [comment]
In the same time you took to create this issue, you could have created a PR instead

**Comment by Berserker66** [comment]
They might simply not know how or where to make the change

**Comment by Mathx2** [comment]
fine, i'll do it myself
