### ISSUE TITLE
Bug: Generate: `generate_output` exception blocks forever and doesn't report the exception

### ISSUE THREAD

**Issue by beauxq** [ArchipelagoMW/Archipelago#2157]
### What happened?

If an `apworld` raises an exception during `generate_output`, `Generate.py` blocks forever and doesn't report the exception.

I had a bug in my `generate_output` (that only happened as `apworld`, not a normal python world folder) and it was hard to figure out what was going on.

### What were the expected results?

see a python trace for the exception

### Software

Local generation

**Comment by Berserker66** [comment]
No, that's if you thread sync block during generate output and don't release the thread block, it should have no bearing on apworld vs. not
