### ISSUE TITLE
Subnautica: Trying to make a tracker, wondering about can_slip_through

### ISSUE THREAD

**Issue by Rashkavar** [ArchipelagoMW/Archipelago#2206]
So, I've started working on a standalone tracker for the AP Subnautica randomizer - something that can provide a bit more information than the excellent but space-limited tracker built into the mod.  First step in this is working out all of the logical restrictions.

So far, I've figured out laser cutter, radiation suit, propulsion cannon, seaglide, and required depth values, and I've found where logical depth is calculated.  But in the Locations.py file, there is also a boolean value "can_slip_through" which is true for only the 2 Grassy Plateaus East Wreck checks (33025 and 33026), which doesn't appear to be checked anywhere in the rest of the Subnautica files.  

I'm guessing this value relates to the fact that these are also considered to be checks that require the laser cutter, but I don't see anything to indicate what implications this value has on logic.  Can anyone explain what this boolean means, and what, if any, impact it has on the logic?

Also as an aside, while I think I understand all of the logical requirements both from a gameplay side and from looking at your code, I'm not 100% certain.  Is there anything other than seed settings, depth, radiation radius, distance from 0,0 and possession of the propulsion cannon and laser cutter that impacts logic?

**Comment by Berserker66** [comment]
Honestly, it can be removed by now and maybe I will bother to do so. It was related to a pre 2.0 glitch that allowed you to clip through without needing the laser cutter.

**Comment by Rashkavar** [comment]
Aha!  Thanks!
