### ISSUE TITLE
Bug: Moving text client onto monitor with different resolution makes the text go nuts

### ISSUE THREAD

**Issue by lioncash** [ArchipelagoMW/Archipelago#2269]
### What happened?

If I move the text client off my default monitor onto my secondary one with a different resolution, the text starts scrolling/flickering after receiving enough new messages that the text client needs to be closed and then reopened to fix it and make it usable again.

My two monitor resolutions are:
1. 2560x1440
2. 3840x2160

Attached is also a (somewhat) janky recording capture of both monitors (once dragged off to the right, coming in from the left it can be considered on monitor 2 above)

https://github.com/ArchipelagoMW/Archipelago/assets/712067/f9507c99-5fc3-4206-9216-7dfe207fafad

### What were the expected results?

That the window would behave like any other normal window

### Software

While playing

**Comment by remyjette** [comment]
This was fixed in #2177. Upgrade to 0.4.3 and the issue should go away.

**Comment by lioncash** [comment]
Oh, good to know, thanks a bunch!
