### ISSUE TITLE
Bug: Python unable to find 'shcore' module in 0.4.3 (Windows 7)

### ISSUE THREAD

**Issue by Ansbaradigeidfran** [ArchipelagoMW/Archipelago#2280]
### What happened?

Having installed Archipelago 0.4.3 on a Windows 7 machine, the launcher, SNI client, and other associated programs do not run when clicked. Running from a command window (or checking the log files) reveals that an uncaught exception occurs when python attempts to access the 'shcore' module.

From a brief online investigation, it appears that shcore.dll is not available for Windows 7, only Windows 8+. This error was encountered having specifically installed the Windows 7 version, which should presumably avoid this.

On installing version 0.4.2, the launcher window opens correctly. It appears that this is therefore a regression from 0.4.2.

[Launcher_2023_10_07_17_54_33.txt](https://github.com/ArchipelagoMW/Archipelago/files/12838332/Launcher_2023_10_07_17_54_33.txt)

### What were the expected results?

Launcher, SNI client, or relevant program should load correctly and display the application window to the user.

### Software

While playing

**Comment by remyjette** [comment]
Fixed by #2246
