### ISSUE TITLE
Bug: Cannot connect to Retroarch bsnes via SNI Client

### ISSUE THREAD

**Issue by rocket0634** [ArchipelagoMW/Archipelago#2426]
### What happened?

I would double click the generated apsmw file and the SNI Client would open, and Archipelago would attempt to automatically open the generated sfc file, which opens WinDSPro by default.
I would manually open Retroarch via Steam, and manually install the mercury-performance core on 1.16.0, and run the generated sfc file. When both SNI Client and bsnes mercury are open, I get the message "No ROM detected, awaiting snes connection to authenticate to the multiworld server (/snes)" and typing /snes results in the message "Already connected to SNES. Disconnecting first." and "Already connected to SNI, likely awaiting a device."

The guides appear to have been written for Retroarch 1.10, so maybe something has changed since updating to 1.16, or otherwise I'm doing something wrong.

Edit: None of the emulators are working, actually.

### What were the expected results?

I believe a message should appear in the SNI Client that says the client is connected when I open the game in Retroarch.

### Software

While playing

**Comment by Hri7566** [comment]
I am experiencing the same issue playing Super Metroid with BizHawk 2.9.1 on Windows 10. I noticed my SNI log has more information, stating that it was unable to correctly check the version of what I believe to be the emulator.

```
2023/11/05 08:09:03.452975 luabridge: accepted connection from 127.0.0.1:56864
2023/11/05 08:09:03.489041 luabridge:127.0.0.1:56864: client 'SNI Connector' version '4' host 'bizhawk' bizhawk: true
2023/11/05 08:09:05.090726 luabridge:127.0.0.1:54131: error while checking version
2023/11/05 08:09:05.090726 luabridge:127.0.0.1:54131: read tcp 127.0.0.1:65398->127.0.0.1:54131: wsarecv: An established connection was aborted by the software in your host machine.
2023/11/05 08:09:05.092721 luabridge:127.0.0.1:54131: connection closed
```

**Comment by rocket0634** [comment]
I joined the server and saw that this was caused by the client not closing SNI properly, which is why none of the games could connect to a new instance of the client.
