### ISSUE TITLE
GAME, The binding of Isaac (repentance)

### ISSUE THREAD

**Issue by imadeagithubaccountforthis** [ArchipelagoMW/Archipelago#2432]
### What feature would you like to see?

![Screenshot 2023-11-04 133443](https://github.com/ArchipelagoMW/Archipelago/assets/81992759/76d47ccd-ecf8-4f8d-9500-bcc826cd8cd7)
i have no idea what to put in this area so have a funny screenshot

**Comment by ScipioWright** [comment]
Please post your suggestions in the future game design channel on the discord instead.

**Comment by imadeagithubaccountforthis** [comment]
aka haha you can't

**Comment by ScipioWright** [comment]
You are allowed to suggest things, just not here. That's what the future game design channel in the discord is for.

**Comment by imadeagithubaccountforthis** [comment]
well anyone looking at this, go suggest this for me (discord sucks)
