### ISSUE TITLE
Docs: Explain why oribf is in worlds_disabled

### ISSUE THREAD

**Issue by wertercatt** [ArchipelagoMW/Archipelago#2468]
### What feature would you like to see?

It is not clear from looking at the repository what caused oribf to be disabled. I believe the problems with it should be written down in worlds_disabled so any potential new maintainers can see what needs to be fixed at a glance.

**Comment by Silvris** [comment]
Specific reasons were given in #1906 but I do think including a document within the directory explaining the issues could be useful, especially should another world ever be disabled. That'd give someone wanting to take over a starting point.

**Comment by ReverM** [comment]
What sould such a file be called? I'm thinking of putting a doc in https://github.com/ArchipelagoMW/Archipelago/tree/main/worlds_disabled

**Comment by wertercatt** [comment]
> What sould such a file be called? I'm thinking of putting a doc in https://github.com/ArchipelagoMW/Archipelago/tree/main/worlds_disabled

REASONS.md, perhaps

**Comment by nicholassaylor** [comment]
This issue has been merged
