### ISSUE TITLE
ALTTP: ALLTP Entrance Randomizer Option - dungeonslimited

### ISSUE THREAD

**Issue by notoriousb1t** [ArchipelagoMW/Archipelago#2493]
### What feature would you like to see?

I'm looking to randomize only the main entrances of ALTTP, but the only option that is close that I can find is dungeonssimple. I really would like to limit the randomization to the main dungeon entrances as possible (with some kind of strategy for dungeons with multiplace entrances like the desert)

a) Is there a better option for this?
b) If not, would a PR be accepted to add it
c) If so, would the preference be to parameterize this with another yaml option or create a new value dungeonslimited, or similar?

**Comment by ThePhar** [comment]
@Berserker66

**Comment by ThePhar** [comment]
Although, I'm not sure I understand the request. How would a propoed `dungeonslimited` differ from `dungeonssimple`?

**Comment by ThePhar** [comment]
Cause I think you could do that with `plando_connections` or whatever it's called.

**Comment by notoriousb1t** [comment]
I only want to randomize the crystal and pendant dungeons. When I ran dungeonsimple, it connected Sahasrahla's house to one of the rupee dungeons, which isn't what I am looking for, just the main dungeons.

But... if I understand you correctly, I should be able to use dungeonssimple and then explicitly connect all the dungeons I don't want randomized via plando_connections. That seems tedious, but would definitely give me what I am looking for. 

Is that what you meant?

**Comment by t3hf1gm3nt** [comment]
Are you absolutely sure you had "dungeonssimple" enabled?
because if it was, sahasrahla's house should not have been touched at all
the "dungeons" ER options only shuffle the pendant/crystal dungeon entrances as well as hyrule castle, agahnim's/castle tower, and ganon's tower
so is this "dungeonslimited" option you are proposing meant to remove hyrule castle, agahnim's/castle tower, and ganon's tower from that pool?

**Comment by notoriousb1t** [comment]
> Are you absolutely sure you had "dungeonssimple" enabled?

I'm not so sure any more. I may have copied the wrong yaml with the simple option instead. This was over a week ago and I have tried to reproduce this a few times with no success. So I think we can attribute this to user error on my part.

As far as "a" listed above, the existing option seems right, I must have made a mistake, and as far as limiting the randomization, plando_connections seems to be an existing parameter which can help me refine this down further. Thank you so much for the help and sorry for the trouble 😄
