### ISSUE TITLE
Bug: Exiting a SC2 mission on completion triggers an e_success error and brings up the Blizzard error reporter

### ISSUE THREAD

**Issue by DylanAPDavis** [ArchipelagoMW/Archipelago#2584]
### What happened?

When exiting a Starcraft 2 mission from the post-mission screen while playing through an ArchipelagoMW, Blizzard's error reporter pops up every time, asking the user if they want to send an error report to Blizzard regarding an "e_success" error. 

![sc2_blizzard_error_report](https://github.com/ArchipelagoMW/Archipelago/assets/5595184/30481fb0-9414-4805-8c53-747bfe0d0c5a)

Looking into the Starcraft II error logs produced when this occurs: 
```
BlizzardCore errors
[0] err=2 text=SFileOpenArchive - SFILE_ERROR_FILE_NOT_FOUND - G:\Games\StarCraft II\Maps\Campaign
```

It appears to be looking for a "Campaign" under Maps. My Maps directory in my Starcraft II directory contains only the "ArchipelagoCampaign" folder, so it seems it doesn't exist on my machine. This is a fresh installation of Starcraft II that was download/installed shortly before running the Archipelago. 

While the user can uncheck the "Send to Blizzard" checkbox to avoid sending Blizzard the error report, so the impact is minor, having to do this every time the user finishes a mission during the randomizer can be annoying. 

I've attached the logs from an ArchipelagoMW session and some of the Starcraft II error logs from that session as well. 

Archipelago logs: 

[Launcher_2023_12_02_18_04_30.txt](https://github.com/ArchipelagoMW/Archipelago/files/13625343/Launcher_2023_12_02_18_04_30.txt)
[Starcraft2Client_2023_12_02_18_05_49.txt](https://github.com/ArchipelagoMW/Archipelago/files/13625344/Starcraft2Client_2023_12_02_18_05_49.txt)

---

Starcraft logs:

[2023-12-02 18.37.36 PC B91115 Error.txt](https://github.com/ArchipelagoMW/Archipelago/files/13625348/2023-12-02.18.37.36.PC.B91115.Error.txt)
[2023-12-02 18.37.36 PC B91115 Error Streaming.txt](https://github.com/ArchipelagoMW/Archipelago/files/13625350/2023-12-02.18.37.36.PC.B91115.Error.Streaming.txt)
[2023-12-02 18.37.36 PC B91115 Error Variables.txt](https://github.com/ArchipelagoMW/Archipelago/files/13625349/2023-12-02.18.37.36.PC.B91115.Error.Variables.txt)

And for fun this is the screenshot Starcraft took at the time of the error:
![2023-12-02 18 37 36 PC B91115 Error](https://github.com/ArchipelagoMW/Archipelago/assets/5595184/ba26d414-49a1-47f5-a0fe-e2f708faad1b)

### What were the expected results?

Either of these two results:

- Exiting a mission does not trigger the e_success error, so the error reporter will not be triggered.
- The error reporter is disabled or suppressed so the user does not have to click to avoid sending a report to Blizzard. 

### Software

While playing

**Comment by t3hf1gm3nt** [comment]
i believe this has been a long standing issue, and iirc, can't/won't be fixed for the forseeable future
though i will poke @Ziktofel for clarification, as the current maintainer

**Comment by DylanAPDavis** [comment]
Thank you for the response, and for the poke! If it ends up being a can't/won't fix, that's alright. It's a quality of life thing, not essential.

**Comment by Berserker66** [comment]
It also seems to be specific to some  players, as I don't get this error.

**Comment by Ziktofel** [comment]
This is being addressed in #2954

**Comment by DylanAPDavis** [comment]
Thank you for addressing the issue, and adding the other campaigns! :)

**Comment by neocerber** [comment]
@DylanAPDavis, it seems that the issue was resolved, could you mark it as closed?

**Comment by DylanAPDavis** [comment]
Sure thing! I forgot to go back and close this. Thanks again!
