### ISSUE TITLE
Bug: FF1: "Terminate Chaos" on non-shards seeds is assumed accessible from the start

### ISSUE THREAD

**Issue by KScl** [ArchipelagoMW/Archipelago#2647]
### What happened?

From a cursory glance at [the source](https://github.com/ArchipelagoMW/Archipelago/blob/main/worlds/ff1/__init__.py#L75), `terminated_event.access_rule` is not set unless there are Shards present in the seed, which means that the game is assumed completable from the very start instead of the intended(?) logic of requiring all key items.

[Spoiler log of an affected seed](https://archipelago.gg/dl_spoiler/k7tweRXOSAaVuFDWz8toyg)
[YAMLs for affected seed](https://github.com/ArchipelagoMW/Archipelago/files/13802228/AP_2023-12-24.zip)

### What were the expected results?

"Terminate Chaos" should be locked behind all key items

### Software

While playing

**Comment by eudaimonistic** [comment]
@jtoyoda FYI

**Comment by jtoyoda** [comment]
Thanks for the fix @wildham0 !
