### ISSUE TITLE
Core: Update docs related to running test 

### ISSUE THREAD

**Issue by ReverM** [ArchipelagoMW/Archipelago#2721]
### What task needs to be completed?

https://github.com/ArchipelagoMW/Archipelago/blob/main/docs/running%20from%20source.md#running-tests and 
https://github.com/ArchipelagoMW/Archipelago/blob/main/docs/tests.md 
both have sections about running test. 

- [ ] Add a link in the running from source doc to the test doc (possibly deleting the whole line)
- [ ] Add an example of what the archipelago directory is supposed to be. I had to do a bit of guess work in order to understand what it was
- [ ] Add information regarding the new button Berserker added

**Comment by black-sliver** [comment]
What new button?

I think we should retain the `pytest`, maybe just as "running tests without PyCharm". Also adding pytest-xdist in there wouldn't hurt: https://github.com/ArchipelagoMW/Archipelago/blob/main/.github/workflows/unittests.yml#L56 is what we do in CI to reduce runtime of tests. On my PC it speeds up tests ~7x ~~and heats the room a lot faster~~.

**Comment by ReverM** [comment]
> What new button?


![image](https://github.com/ArchipelagoMW/Archipelago/assets/104455676/29cfe154-294e-4af0-a920-6c937d93ca13)

**Comment by black-sliver** [comment]
Oh, unless I am mistaken that button isn't actually "new". It's just now hopefully always pre-configured to work.

**Comment by ReverM** [comment]
The doc should still mention it I think

**Comment by black-sliver** [comment]
Yeah, showing how to run tests is a good idea. I was just confused by the wording
