### ISSUE TITLE
Bug: Sending a `[` adds `[/color]` to the message

### ISSUE THREAD

**Issue by Eijebong** [ArchipelagoMW/Archipelago#2742]
### What happened?

Someone sent `>:[` in the text client, we got `>:[[/color]` instead.

### What were the expected results?

I would expect the received message to be the same as the one sent `>:[`

### Software

While playing

**Comment by black-sliver** [comment]
Fixed in https://github.com/ArchipelagoMW/Archipelago/pull/3659
Will be in the next release.
