### ISSUE TITLE
Bug(Hollow Knight): Either Fragile/Breakable charm pair counted as 2 charms, or a single King Fragment counted.

### ISSUE THREAD

**Issue by cmcoffin** [ArchipelagoMW/Archipelago#2873]
### What happened?

Had a seed where I needed 14 charms to buy a required item(Monarch Wings). There were only 13 charms available to me however. I had an unbreakable charm, which the logic might have double counted, and I also had a single Kings Fragment. Attached are yamls and spoiler log.
Note: I've redacted the names for privacy's sake
Note2: I accidentally set charm costs to custom and didn't do a plando. Don't know if that could have affected it.

### What were the expected results?

To have enough charms :)

### Software

While playing

**Comment by Silvris** [comment]
Fixed in #2683, will be present on the next release.

**Comment by cmcoffin** [comment]
Cool, thanks.
Do you know which case it was, out of curiosity?

**Comment by BadMagic100** [comment]
I'm going to close this since a fix is merged, otherwise it's never gonna get closed lol
