### ISSUE TITLE
InnoSetup: During setup LTTP sprite download can be inadvertently interrupted during installation.

### ISSUE THREAD

**Issue by Drexl** [ArchipelagoMW/Archipelago#3204]
### What happened?

After setup of 0.4.6 you are prompted to restart windows while LTTP sprites are still downloading, potentially interrupting the process.

### What were the expected results?

All setup procedures would be completed before being prompted to restart windows.

### Software

Local generation

**Comment by ThePhar** [comment]
Interesting. Not much work has been done on the innosetup script in a while, but if no one else does, I'll see if I can take a look when I have the time.

**Comment by alwaysintreble** [comment]
The installer doesn't need you to restart windows and doesn't prompt for it. I just tested it. Whatever prompted you to restart was not the Archipelago installer.

**Comment by ThePhar** [comment]
> The installer doesn't need you to restart windows and doesn't prompt for it. I just tested it. Whatever prompted you to restart was not the Archipelago installer.

I presume it's the Visual C++ Redistributable actually. It would also only request a restart if it was the first time installed.

**Comment by Berserker66** [comment]
It is visual C++ redist, yes. The way it works is that when a windows component like it is updated or installed a flag is set that will cause all future setups, including ours, to ask for a restart. You can  get the same if you run any other windows setup before the shutdown get the same question.

**Comment by nicholassaylor** [comment]
This should be fixed now as the installer will wait for sprites to finish downloading before continuing to the end of set-up.
