### ISSUE TITLE
Bug: TextChoice does not work properly when creating a yaml from the webhost in 0.4.7

### ISSUE THREAD

**Issue by ScipioWright** [ArchipelagoMW/Archipelago#3367]
### What happened?

Running webhost on main, when generating a TUNIC game with default settings (just hitting the "generate single player game" button), it states `entrance_rando-custom is not a valid option name for TUNIC and is not present in triggers.`
When exporting the yaml, it has the line `entrance_rando-custom: ''` directly under the regular entrance rando option.

Additionally, when generating a TUNIC game with the entrance rando option set to "tunc", the spoiler log of the generated game shows that the entrance rando option is set to "custom".
~~Furthermore, when using that yaml as a weights.yaml and generating a 20 slot multiworld with it, the first slot has the entrance rando option set to "custom" and every other slot has the entrance rando option set to No (which disables it).~~
edit: this was an unrelated issue: https://github.com/ArchipelagoMW/Archipelago/pull/3381

### What were the expected results?

If Entrance Rando is set to No, the yaml should have `entrance_rando: 'no'`.
If Entrance Rando is set to Yes, the yaml should have `entrance_rando: 'yes'`.
If Entrance Rando is set to the custom string `tunc`, the yaml should have `entrance_rando: 'tunc'`.

### Software

Website

**Comment by ScipioWright** [comment]
Update: TextChoice doesn't seem to work properly with a weights.yaml file.
Attached is a weights.yaml (renamed to txt so I can attach it)
[weights.txt](https://github.com/ArchipelagoMW/Archipelago/files/15407273/weights.txt)

If you try to generate with this with multiple slots, it will correctly set the first slot's entrance rando option to `tunc`
And then every other slot it will set it to No

**Comment by LegendaryLinux** [comment]
Fixed in https://github.com/ArchipelagoMW/Archipelago/pull/3390
