### ISSUE TITLE
Bug: Spoiler logs are not generated when clicking "Generate Single-Player Game" in 0.4.7

### ISSUE THREAD

**Issue by ScipioWright** [ArchipelagoMW/Archipelago#3378]
### What happened?

When generating a single player game by pressing the Generate Single-Player Game button on the options page for a game, it does not generate the spoiler log (or at the very least did not provide a link to view the spoiler log).

### What were the expected results?

I expected it to generate a spoiler log.

### Software

Website

**Comment by Exempt-Medic** [comment]
Fixed in [3411](https://github.com/ArchipelagoMW/Archipelago/pull/3411)
