### ISSUE TITLE
Launcher: Make it so you can add an icon to your client without modifications to core

### ISSUE THREAD

**Issue by ScipioWright** [ArchipelagoMW/Archipelago#3387]
### What feature would you like to see?

Currently, to have an icon on your client button in the launcher, it requires putting the icon in the `Archipelago/data folder`, and a modification to `Archipelago/worlds/LauncherComponents.py`.

It should probably just let you put the icon in your apworld and put the icon on the button in the launcher without modifications to core.

**Comment by nicholassaylor** [comment]
With #3629, this should be solved
