### ISSUE TITLE
Bug: Orange Islands South Hidden Chest

### ISSUE THREAD

**Issue by evierose04** [ArchipelagoMW/Archipelago#3399]
### What happened?

In the past few times I've played A Short Hike multiworld, I noticed in the tracker that there were checks for "Orange Islands South _Hidden_ Chest" and "Orange Islands South _Buried_ Chest", and it has confused me.

### What were the expected results?

[https://voxelse.github.io/aShortHike/interactiveMap/](url)
I've looked at the interactive map and have only found one item in the area that appears there in vanilla, but the randomizer treats it as if there are two chests in that area (generating it as a check and putting an item there). I've done 2-3 multiworlds where I've had this check open, and I haven't found it in all my scouring of the island.

Is the hidden chest an error by the randomizer generating the buried chest twice, or the chest is missing? 

### Software

Website

**Comment by SephDB** [comment]
The orange islands south hidden chest is the chest hidden from view at the southernmost tip of the island:
![image](https://github.com/ArchipelagoMW/Archipelago/assets/861510/c86761ac-bbed-4c23-9b37-ffca3ad12dd4)
It's the 13-coin chest on the island that also houses the stormy view map.

While the south island buried chest is on another island altogether, on the other side of the orange islands:
![image](https://github.com/ArchipelagoMW/Archipelago/assets/861510/c4910efe-3533-4574-adbf-bed6a7cae1fa)
(on the interactive map it's the 13-coin buried chest on the southwest island)

On the interactive map:
![image](https://github.com/ArchipelagoMW/Archipelago/assets/861510/1fad16c3-16cf-47c8-8241-b1b1eb947818)

**Comment by evierose04** [comment]
Ah, I see. Thank you. None of the other items mention that island being south, so I was under the impression the south island was just the one small island.
