### ISSUE TITLE
Bug: 0.5.0 RC1 - Weighted Options page shows random and random range for toggles and choices

### ISSUE THREAD

**Issue by ScipioWright** [ArchipelagoMW/Archipelago#3431]
### What happened?

In the 0.5.0 RC1, and on the beta site currently, things that should not have random-low, random-middle, or random-high have those.

http://archipelago.gg:24242/games/The%20Witness/weighted-options

![image](https://github.com/ArchipelagoMW/Archipelago/assets/24858499/3af84a75-26db-4b9d-9c38-7ba690274030)

### What were the expected results?

Toggles just having "No" or "Yes". Choice probably just having the individual choices, since having random there is unnecessary since it's the weighted options page.
Maybe other type are wrong too, didn't look for every scenario.

### Software

Website

**Comment by LegendaryLinux** [comment]
Fixed in https://github.com/ArchipelagoMW/Archipelago/pull/3448.
