### ISSUE TITLE
Bug: Zork Grand Inquisitor progression bug

### ISSUE THREAD

**Issue by fongoid** [ArchipelagoMW/Archipelago#3559]
### What happened?

https://archipelago.gg/dl_spoiler/Fh3KuSyGQcGUZYLNkjSQ4g

In order to get `YASTARD` I needed the `Mug`. The `Mug` was locked behind the location `That's Still a Rope`. `That's Still a Rope` requires the `GLORF` spell, which was locked behind the `GUE Tech Entrance Exam`, which requires `REZROV`, which was locked behind location `Down`. `Down` requires the `YASTARD` spell.

### What were the expected results?

To be able to progress without using `/send_location`

### Software

While playing

**Comment by nbrochu** [comment]
You can get to GUE tech in 2 other ways. It doesn't necessarily require REZROV

**Comment by nbrochu** [comment]
Yeah I just looked at the spoiler you provided and the logic is fine.

Sphere 3: You got Teleporter Destination: Spell Lab
Sphere 4: You got Map. You can teleport to Spell Lab.

Once in Spell Lab, you can navigate backwards to the lobby of GUE Tech and in there, take the window out and go do Entrance Exam to get GLORF. Finally, go back to crossroads and get the rope back with GLORF and teleport again to Spell Lab to show the guard the rope.

You probably didn't know about the window in GUE Tech that takes you outside to Entrance Exam area

**Comment by fongoid** [comment]
> You can get to GUE tech in 2 other ways. It doesn't necessarily require REZROV

I mistakenly didn't try to backtrack over the bottomless pits 🤦‍♂️ Just verified.

Closed.

**Comment by nbrochu** [comment]
Yeah the bottomless pits are actually covered when going backwards, but not if you turn around. The joys of prerendered graphics
