### ISSUE TITLE
Generate crash in Super Metroid minor_qty

### ISSUE THREAD

**Issue by beauxq** [ArchipelagoMW/Archipelago#360]
This crash is in ~both 0.2.5 through the website and~ latest main branch.
(I forgot the website saves settings. It looks like it's not an issue in 0.2.5)

I narrowed this crash down to this setting.
If SM's minor_qty is anything but 100, it crashes.

You can use the website https://archipelago.gg/games/Super%20Metroid/player-settings
and lower "Minor Quantity" and then press ~"Generate Game"~ "Export Settings"

or use this yaml:
```
Super Metroid:
  minor_qty: 22
game: Super Metroid
name: b
```

```
Traceback (most recent call last):
  File "Generate.py", line 661, in <module>
    main()
  File "Generate.py", line 207, in main
    callback(erargs, seed)
  File "/home/user/code/Archipelago/Main.py", line 413, in main
    multidata_task.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/user/code/Archipelago/Main.py", line 364, in write_multidata
    assert location.item.code is not None, "item code None should be event, " \
AssertionError: item code None should be event, location.address should then also be None
```

**Comment by beauxq** [comment]
Lowering the "Energy Quantity" does not have the problem. It does not crash when it gets to the `NoEnergy` item.

It crashes when it gets to the `Nothing` item, which is a placeholder for minor items.

**Comment by Berserker66** [comment]
@lordlou

**Comment by Alchav** [comment]
> @lordlou @Alchav

> AssertionError: item code None should be event, location.address should then also be None

You changed it from address = None to code = None, @Berserker66

**Comment by Berserker66** [comment]
hopefully fixed in https://github.com/ArchipelagoMW/Archipelago/pull/363 then

**Comment by Ijwu** [comment]
@beauxq Any chance you can attempt this again with the recent release and let us know if it is fixed?

**Comment by beauxq** [comment]
> @beauxq Any chance you can attempt this again with the recent release and let us know if it is fixed?

Yeah. Generate.py does not crash with that yaml now.
