### ISSUE TITLE
New Feature Request: Starcraft 2; Nova color selection in options page

### ISSUE THREAD

**Issue by StormyStrife** [ArchipelagoMW/Archipelago#3610]
### What feature would you like to see?

Nova color field in the generate game options page of Starcraft 2 is what I'd like to see. What code can I add into my yamls to apply a new color to Nova in the meantime?

**Comment by ScipioWright** [comment]
I'd recommend asking for this in the Starcraft 2 channel on the discord. I doubt they're going to look here.
