### ISSUE TITLE
(Celeste 64) "Key Not Found Exception" when trying to get past file selection screen

### ISSUE THREAD

**Issue by NARbluebear** [ArchipelagoMW/Archipelago#3638]
### What happened?

I booted up Celeste 64 to see if I had any more checks I could reach, but as soon as I loaded the file the game crashed. It was fine yesterday, so my guess as to what happened is that someone (somehow) managed to send me an invalid item, and C64 couldn't comprehend it.
![image](https://github.com/user-attachments/assets/6a4253a8-d11a-44b4-84d7-48f3a39e3974)
[ErrorLog.txt](https://github.com/user-attachments/files/16198095/ErrorLog.txt)

### What were the expected results?

When I load up the save, I expected to be put right back at the start with the strawberries and cassettes I've already found being transparent.

### Software

While playing

**Comment by Exempt-Medic** [comment]
@PoryGone it's the ID for Raspberry btw

**Comment by Exempt-Medic** [comment]
Some more information may be helpful here, like a link to the room, the version of Archipelago this room was generated with. Also are you using version 1.1 instead of 1.2 for some reason?

**Comment by NARbluebear** [comment]
My bad, it was an issue with me using v1.1. I wasn't even aware v1.2 existed. Here's a link to the room regardless, not that it would help: https://archipelago.gg/room/R5v7n4oRSQmA38_-Q4uvBg. I'm unsure of what version of AP it was generated with.
