### ISSUE TITLE
Bug: SC2 vanilla mission order sometimes allows playing missions with their prerequisites unlocked but not completed

### ISSUE THREAD

**Issue by Hardrocknerd** [ArchipelagoMW/Archipelago#3642]
### What happened?

I am playing SC2 (all campaigns except Nova: Covert Ops) in a multi-world with vanilla mission order. In the later parts of the playthrough I started to notice I had some missions unlocked for which I had not actually completed the (in vanilla) required prerequisites, had however already _unlocked_ those missions.

See screenshot of my Archipelago client below:
![APSC2Client](https://github.com/user-attachments/assets/3422795a-727a-497e-a0cb-f27d88b3d142)

To name some visible examples from this screenshot:
- I can play Into the Void without having played All-In, usually a prerequisite.
- I have played The Reckoning without having played Death from Above, the required mission directly before it.
- I can play All-In without having played Supernova and Maw of the Void, usually prerequisites.

There are several more examples as well; the mission order is simply much less restrictive than it actually is in vanilla.

### What were the expected results?

I expected several missions to be locked until I had played their usual prerequisites in vanilla Starcraft 2 (see examples above). Potentially I am misunderstanding what vanilla mission order means for Archipelago purposes, but I think some progression logic is simply not working correctly atm.

### Software

While playing

**Comment by Bicoloursnake** [comment]
Question, is this a solo game or a multiworld, and if it's a multiworld, is collect on? I have a sneaking suspicion that some of your victory locations may have been collected out, which AP SC2 considers the same as beating a mission.

**Comment by Hardrocknerd** [comment]
It was indeed a multiworld and we indeed had collect on; that explains it then. Not the behaviour I would intuitively have expected, but I'll close the issue then, as this is actually intended.
Thanks for clearing this up for me! :)
