### ISSUE TITLE
Bug: Hollow Knight: Missing Logic: Require Focus before entering Black Egg Temple and fighting HK.

### ISSUE THREAD

**Issue by NebuPookins** [ArchipelagoMW/Archipelago#3643]
### What happened?

Was playing Archi with a friend, and they never found Focus, but they found the three dreamers. So they showed up at the Black Egg Temple which opened up, and then went in and fought the Hollow Knight. Once the Hollow Knight was defeated, my friend could not actually absorb the infection from HK because she did not have Focus. She force quit the game and reloaded the save, but now it was in a weird corrupted state, like locations no longer giving the checks they're supposed to.

### What were the expected results?

Don't let the player fight HK unless they have Focus. Perhaps the easiest way to implement this is to make the Black Egg Temple only open up with you have 3 dreamers AND Focus?

### Software

While playing

**Comment by Exempt-Medic** [comment]
You can walk out of the fight arena in that case

**Comment by BadMagic100** [comment]
As stated you are able to leave the room if you don't have focus, and logic does require you to have focus for the goal to be in logic. Closing this as won't fix.
