### ISSUE TITLE
Bug: Generation refreshes site permanently for Subnautica room

### ISSUE THREAD

**Issue by Krasioletto** [ArchipelagoMW/Archipelago#3694]
### What happened?

I just tryed to set up a lobby and config-site worked perfect as always. But then the "Generation in Progress" site won't stop refreshing. It's 10 mins now. 

### What were the expected results?

I thought it would just puke out a room 

Man I don't know this site. What you want to hear? I expected it to work xD

### Software

Website

**Comment by ScipioWright** [comment]
There were problems with website generation.
If it happens again in the future, you can generate locally then upload the output to the site. You can find how to do that by reading the Setup Guides on the website, or you can ask in the discord.
