### ISSUE TITLE
Bug: In Starcraft 2, loading a save or restarting a mission crashes the game

### ISSUE THREAD

**Issue by SwooshyCueb** [ArchipelagoMW/Archipelago#3696]
### What happened?

Whenever I try to load a save or restart a mission from the ingagme menu in Archipelago Starcraft 2, the game crashes. This means that if I miss a check or fail an objective, I have to start the entire mission over again. Considering there are missions where you have objectives like defending a structure for thirty realtime minutes, I feel this is unacceptable.

If it matters, I'm playing the game in Proton, specifically GE-Proton9-10. I am not using the AppImage, but launching the SC2 client from the tarball.

### What were the expected results?

I expect that when I restart a mission from the ingame menu or load a save made during that session, the game should do the thing instead of crashing.

### Software

While Playing

**Comment by MatthewMarinets** [comment]
Save/load is not supported in Archipelago Starcraft 2, and likely won't be as it would take a significant rework of the infrastructure used to communicate with the game.

This is one of the reasons why we recommend doing a first playthrough one difficulty lower than a player's comfortable vanilla playthrough difficulty, and we design our logic rules with lack of saving in mind. Difficulty can be changed between missions with the `/difficulty` command in the client.

If the player is getting very frustrated or just wants to skip a mission, it's possible to get the locations from the server command line (ie the text box in the room page), using a `/send_location [slot name] [location name]`. It's also possible to use cheats to fly clear through a mission, like "terribleterribledamage".

A rudimentary checkpoint system is under discussion for some missions that have hard breaks or no-build segments, such as Enemy Intelligence, Belly of the Beast, etc

**Comment by SwooshyCueb** [comment]
Is this documented somewhere? If not, it probably should be. If it is, apologies for missing it.

**Comment by MatthewMarinets** [comment]
I couldn't find it in a quick search of the docs, will see about getting it added to the Game Page / Setup Guide.

**Comment by MatthewMarinets** [comment]
Seems neocerber is already way ahead of me, #3440 adds this information to the docs (among other things).

**Comment by ScipioWright** [comment]
Gonna close this cause a PR has been opened to address it already. Feel free to reopen it if you think it shouldn't be closed yet.
