### ISSUE TITLE
SM: 0.3.0 crashes old games on load and corrupts SRAM for downgrade

### ISSUE THREAD

**Issue by strotlog** [ArchipelagoMW/Archipelago#389]
Per multiple reports from players of the ongoing community SM async game (which started 4 days ago on AP 0.2.5):

Steps:
1) Play part of seed on Archipelago 0.2.5
2) Upgrade to 0.3.0
3) Attempt to continue the seed

Bug part 1: SM crashes on load before Samus is able to move.
Bug part 2: Players rolled back their Archipelago to 0.2.5 to work around Bug part 1, but the crash remained. Likely cause would be that attempting to play with 0.3.0 client puts something into SRAM that the 0.2.5 ROM doesn't understand, and SRAM persists past the rollback. Players must delete their save to continue the seed, losing all local progress.

**Comment by Berserker66** [comment]
@lordlou

**Comment by lordlou** [comment]
Thats bad. I'll work on a fix ASAP. Also, I think I can manage a script (python) to fix affected SRAM, if its not too late.

**Comment by lordlou** [comment]
PR submitted here: https://github.com/ArchipelagoMW/Archipelago/pull/400
