### ISSUE TITLE
Fill in the Windows file version for the Setup.exe

### ISSUE THREAD

**Issue by Ijwu** [ArchipelagoMW/Archipelago#39]
This thing.

![image](https://user-images.githubusercontent.com/1393017/128244681-6b29f9c2-2aff-4aed-9d0e-a229192fe102.png)

**Comment by Berserker66** [comment]
addressed in https://github.com/ArchipelagoMW/Archipelago/commit/4b38cb4c2e8a511c9ea68017a798f418b8a53595
