### ISSUE TITLE
Bug: OSRS option names do not display correctly

### ISSUE THREAD

**Issue by nicholassaylor** [ArchipelagoMW/Archipelago#3946]
### What happened?

![image](https://github.com/user-attachments/assets/718b76e9-6721-484d-8e22-46332d86ca26)
Image taken from the beta site

### What were the expected results?

Image does not have underscored names

### Software

Website

**Comment by Exempt-Medic** [comment]
@digiholic Although this isn't a bug. If we wanted to force every option to use a display name, we would
