### ISSUE TITLE
Bug: Pokemon Emerald Match Call rematches do not work

### ISSUE THREAD

**Issue by m4-used-rollout** [ArchipelagoMW/Archipelago#3959]
### What happened?

In Pokemon Emerald, you can use the PokeNav's Match Call feature to call trainers for a rematch if they have a Poke Ball icon next to their name. In this patch, that doesn't work.

Here is a video attempting to rematch Lady Cindy on Route 104 in Archipelago Emerald.

https://github.com/user-attachments/assets/1d166de7-f8a4-4bfd-8f74-a47626fda362

### What were the expected results?

Walking up and talking to the trainer should start a rematch.

Here is a video attempting to rematch Lady Cindy on Route 104 in vanilla Emerald.

https://github.com/user-attachments/assets/5e219830-dac1-4895-94b5-976c1d670270

(The messages the trainer says over the phone are random and aren't related to whether or not they will rematch you)

These rematches give the player a way to get more cash if they run out and have trouble making progress without supplies. It would be nice to have them.

### Software

While playing

**Comment by m4-used-rollout** [comment]
Is the source code for the patch available anywhere? It would make it possible to help diagnose issues like this. It would also make building tools that work with it far easier. 
It would also allow people to contribute pull requests that could help fix save compatibility with vanilla Emerald so other tools people might want to use can still work.

**Comment by KScl** [comment]
This is not a bug. Rematches are currently intentionally disabled.

**Comment by m4-used-rollout** [comment]
Oh. You might want to note that on the Pokémon Emerald Game Page.
Is there a particular reason to disable them? Not only are they a way to solve money problems but they also help pass the time if you're waiting for an item to be found.
