### ISSUE TITLE
Bug: FFMQ in Bizhawk/SNI automatically collects and releases all items when save data is present

### ISSUE THREAD

**Issue by zpunorm22** [ArchipelagoMW/Archipelago#3996]
### What happened?

Tested with 0.5.0 on Arch Linux.
* Generate a multiworld with Final Fantasy Mystic Quest
* Open said game in Bizhawk, connect it to the Archipelago server and reach the overworld
* Save the game in the menu
* Reset the game
* Result: All items and checks related to the game are gotten

### What were the expected results?

* Gameplay should continue as normal

### Software

While playing

**Comment by Exempt-Medic** [comment]
@wildham0

**Comment by wildham0** [comment]
i think this pr fixes it, is it live?
https://github.com/ArchipelagoMW/Archipelago/pull/3710
@Alchav would know more

**Comment by ScipioWright** [comment]
#3710 got merged, so this has been resolved
