### ISSUE TITLE
Website: Better /api/generate endpoint

### ISSUE THREAD

**Issue by zabory** [ArchipelagoMW/Archipelago#4047]
### What feature would you like to see?

I would love to see the ability to add custom worlds to the generate API endpoint. Possibly another file called world in the post request form? Anything works though

**Comment by Berserker66** [comment]
Due to security issues, that's a long term plan probably months, possibly years out still, as we either need apworlds with non-executable code or an isolated sandbox solution.

**Comment by NewSoupVi** [comment]
The idea being that apworlds are essentially arbitrary executable code, so this would mean we'd let you upload whatever code you want to run on our server. Hopefully that makes it somewhat obvious why we can't do this. We need to continue to approve apworlds individually.

**Comment by zabory** [comment]
Oh yeah 100%. Thanks for the replies!
