### ISSUE TITLE
Launcher: Discord invites are invalid

### ISSUE THREAD

**Issue by harperposten** [ArchipelagoMW/Archipelago#4072]
The discord invites are invalid. This includes the regular one linked everywhere and the Unrated/18+ linked on the launcher.

**Comment by ThePhar** [comment]
I just tested them and they work for me. Can you provide the URL it is attempting to send you?

**Comment by harperposten** [comment]
https://discord.com/invite/8Z65BR2

It does work on my phone, so it's probably an issue with Firefox or maybe uBlock somehow, but the invite itself is definitely fine!
