### ISSUE TITLE
Bug: Zelda 1 Seed impossible to complete

### ISSUE THREAD

**Issue by adeeb1** [ArchipelagoMW/Archipelago#4102]
### What happened?

Seed #: 27340806563706762318
Archipelago version (from the website): 0.5.0

I was playing a Zelda 1 multiworld with one other person, and it is impossible for us to get all of the items to complete the game. There are two main issues:

1. Despite getting the Letter, we cannot give it to the Old Woman. There is no item in our inventory to give her, and visiting her in all of the potion shops has not resulted in her recognizing that we have the letter. As a result, all of the potion shops are inaccessible, and we cannot complete the checks for "Potion Shop Item Left," "Potion Shop Item Middle," and "Potion Shop Item Right."
2. The "Take Any Item" shop can only be accessed once, but there are three tracker items for it: 1) Take Any Item Left; 2) Take Any Item Middle; 3) Take Any Item Right. If you happen to choose one and miss out on a key item like a Triforce Fragment, it's impossible to get that key item. Ideally, you would either be able to access this shop multiple times or the randomizer would know not to put a key item there since completion could be impossible.

The situation we're in is that none of the players can access the Level 9 dungeon because we don't have enough Triforce Fragments. The only Triforce Fragment that's accessible outside of Level 9 for one of the players is in the "Take Any Item Left" check. However, since the "Take Any Item Middle" check was chosen instead, it's impossible to complete the aforementioned check and get the last accessible Triforce Fragment.

Here are the configuration settings used:

```
Filling Algorithm: balanced
Players: 2
Progression Balancing: 50
Accessibility: Locations
Local Items:
Non-local Items:
Start Inventory:
Start Hints:
Start Location Hints:
Excluded Locations:
Priority Locations:
Item Links:
Expanded Item Pool: Yes
Triforce Locations: Anywhere
Starting Position: Safe
```

### What were the expected results?

I am able to successfully beat the game and unblock the other player.

1. We are able to give the letter to the Old Woman to access the potion shops so that we can complete all of the checks: 1) Potion Shop Item Left; 2) Potion Shop Item Middle; 3) Potion Shop Item Right.
2. The "Take Any Item" shop can be accessed multiple times OR the randomizer would not put a key item in the shop since completion could be made impossible.

### Software

Website

**Comment by Exempt-Medic** [comment]
@t3hf1gm3nt @Rosalie-A

**Comment by NewSoupVi** [comment]
From user Reg on the Discord:

> None of the take any items are in logic until you have access to all the take-any caves. If you go through all of the take-any caves and don't select one (or more) of the items (And instead choose to continually re-select one you've already gotten), you'll be automatically given the others

If a PopTracker pack is claiming otherwise, I assume it is lying to you

**Comment by t3hf1gm3nt** [comment]
1) Are you absolutely sure you don't have the Letter in your inventory? It is in the same slot as potions/waters of life, so you do need to use any up that you might have. Once you've used them, the letter should be in it's place. This should give you access to the Potion Shop locations
2) There are 4 Take Any Caves in the game, and none of the "Take Any Item" shop locations are in logic until you have access to all 4, which requires bombs and the raft. There are protections in place in the client/connector lua that once all four Take Any Cave's have been visited and an item selected out of them, if there are any remaining "Take Any Item" AP locations that have not been sent, it will send the unsent locations out.

Please confirm that you have checked out both of these and if it resolves the issue you are having

**Comment by adeeb1** [comment]
> 1. Are you absolutely sure you don't have the Letter in your inventory? It is in the same slot as potions/waters of life, so you do need to use any up that you might have. Once you've used them, the letter should be in it's place. This should give you access to the Potion Shop locations
> 
>     2. There are 4 Take Any Caves in the game, and none of the "Take Any Item" shop locations are in logic until you have access to all 4, which requires bombs, a candle and the raft. There are protections in place in the client/connector lua that once all four Take Any Cave's have been visited and an item selected out of them, if there are any remaining "Take Any Item" AP locations that have not been sent, it will send the unsent locations out.
> 
> 
> Please confirm that you have checked out both of these and if it resolves the issue you are having

@t3hf1gm3nt Thank you. You are correct, and this is our mistake. We were able to get the letter by using up our existing potions and give it to the Old Woman.

We were also able to find the other "Take Any Item" shop locations and get the remainder of the items so that we can complete our quest. We missed some shops that we thought we had visited.

Thank you for your support, and apologies for the trouble.
