### ISSUE TITLE
Bug: Pokémon Emerald options generator makes it impossible to generate vanilla TM/HM learnsets

### ISSUE THREAD

**Issue by tikatoo** [ArchipelagoMW/Archipelago#4159]
### What happened?

* I set the "TM/Tutor Compatibility" and "HM Compatibility" dropdowns to "Vanilla (-1)"
* I downloaded the options file, and used that to generate a game with friends
* The file contained the following contents:
  ```yaml
    tm_tutor_compatibility: '0'
    hm_compatibility: '50'
  ```
* No Pokémon can learn any TMs, and HM compatibility is randomly distributed

### What were the expected results?

I expected the options file to look something like this:
```yaml
  tm_tutor_compatibility: '-1'
  hm_compatibility: '-1'
```
And for the resulting game to have vanilla behaviour for TMs and HMs.

Manually setting these properties in the options file appears to have no issues with validation.

### Software

Website

**Comment by Exempt-Medic** [comment]
This is a known bug and is fixed in the next release of Archipelago
