### ISSUE TITLE
Bug: Hollow Knight - Unreachable required item

### ISSUE THREAD

**Issue by Shadow-Night-Black** [ArchipelagoMW/Archipelago#4186]
### What happened?

Generated and was playing a hollow knight randomiser (single world/game), using archipelo map mod to keep track of checks. Apon getting every check available to me and being unable to progress, I checked the spolier log to see progression. The log indicated that Mantis claw was the next progression item to get, and to find it at Markoth. Unfortuneatly, due to not having wings/claw I am unable to reach Markoths room (map mod correctly displays this as unreachable).

[AP_25904193892724614609_Spoiler.txt](https://github.com/user-attachments/files/17738056/AP_25904193892724614609_Spoiler.txt)

### What were the expected results?

Deepnest_East_10 should not be in logic without Wings/Claw

### Software

Local generation

**Comment by qwint** [comment]
looks like this is another previously-undocumented background pogo so current logic just assumes you can always do the background pogo

**Comment by Shadow-Night-Black** [comment]
Can confirm, with the knowedge that I needed a background object pogo, I was able to reach markoth.

**Comment by ScipioWright** [comment]
Closing because iirc there's already some logic rewrites going on, and the world maintainer now knows about the issue, so it's safe to say this doesn't need to be up here anymore
