### ISSUE TITLE
Bug: Pokemon Emerald: Possible inccorect variable used in data.py

### ISSUE THREAD

**Issue by Mysteryem** [ArchipelagoMW/Archipelago#4329]
### What happened?

I followed an IDE warning, about use of variables that might not be assigned, while looking at `data.py` and these couple of lines of code use the `encoded_warp` variable which was last used much earlier in the `_init()` function as the loop variable of a loop nested within another loop. The code does not seem correct, but I have no idea what it is supposed to be doing.

Previous use of `encoded_warp`:
https://github.com/ArchipelagoMW/Archipelago/blob/ac8a206d4685e015494dd67f9a9e7ab2411773b3/worlds/pokemon_emerald/data.py#L509-L515

Potentially problematic code (lines `1462` and `1463`):
https://github.com/ArchipelagoMW/Archipelago/blob/ac8a206d4685e015494dd67f9a9e7ab2411773b3/worlds/pokemon_emerald/data.py#L1458-L1463

@Zunawe 

### What were the expected results?

It shouldn't be that the code should have been using the `warp` variable, because line `1460` ensures that `warp` is in `data.warp_map`. So checking `if warp not in data.warp_map:` would make no sense.

And it shouldn't be that the code is meant to be using the `encoded_warp` variable because it is not is not mutated inside the loop, so lines `1462` and `1463` would not need to be inside the loop.

For these reasons, I have no idea what the correct code could even be here.

### Software

Local generation

**Comment by Zunawe** [comment]
Most likely a copy/paste leftover or something. Or maybe `extracted_data` had a different shape previously, and the refactor missed these lines. I'm fairly confident the intention would have been what is currently achieved by `None if destination == ""`. That is, set the destination to `None` if it goes nowhere. It's almost certainly deletable, so I'll make a PR for that.
