### ISSUE TITLE
Accessibility: minimal sometimes runs out of locations to place items

### ISSUE THREAD

**Issue by Jarno458** [ArchipelagoMW/Archipelago#434]
This is mostly apparent when using one game with a lot of progression items, and a 2nd game with a lot of progression gates setting accessibility: minimal on the 2nd game. This was reproduce with the following combinations of games
Archipidle + Timespinner
Archipidle + Super Metroid
Archipidle + AlttP

As example i included two [Yamls.zip](https://github.com/ArchipelagoMW/Archipelago/files/8455640/Yamls.zip) tested on [AP 3.4.0](https://github.com/ArchipelagoMW/Archipelago/commit/f716bfc58faf406ee2a6020eb9d86a59cc7657f4) using seed **55934839902109730105**

Generation output:
T:\Git\Archipelago>Generate.py --seed 55934839902109730105
P1 Weights: Jarno_Pudle.yaml >> No description specified
P2 Weights: SMJarno.yaml >> Generated by https://archipelago.gg/
Generating for 2 players, 08473603582407276377 Seed 55934839902109730105 with plando: bosses
Archipelago (0.3.4) logging initialized.
Archipelago Version 0.3.4  -  Seed: 55934839902109730105

Found World Types:
  A Link to the Past          : 144 Items (IDs:        2 -      180) | 287 Locations (IDs:    59758 -  4194341)
  ChecksFinder                :   3 Items (IDs:    80000 -    80002) |  25 Locations (IDs:    81000 -    81024)
  Dark Souls III              : 320 Items (IDs:   100000 -   100319) | 324 Locations (IDs:   100000 -   100323)
  Donkey Kong Country 3       :   8 Items (IDs: 14430208 - 14430215) | 191 Locations (IDs: 14430208 - 14430398)
  Factorio                    : 222 Items (IDs:   131070 -   131292) | 183 Locations (IDs:   131072 -   131254)
  Final Fantasy               : 192 Items (IDs:      256 -      498) | 255 Locations (IDs:      257 -      767)
  Hollow Knight               : 249 Items (IDs: 16777216 - 16777464) | 740 Locations (IDs: 16777216 - 16777955)
  Meritous                    :  23 Items (IDs:   593000 -   593022) | 104 Locations (IDs:   593000 -   593103)
  Minecraft                   :  46 Items (IDs:    45000 -    45100) | 114 Locations (IDs:    42000 -    42113)
  Ocarina of Time             : 148 Items (IDs:    66001 -    66202) | 663 Locations (IDs:    67010 -    67673)
  Raft                        : 325 Items (IDs:    47001 -    47325) | 154 Locations (IDs:    48001 -    48155)
  Rogue Legacy                :  76 Items (IDs:    90000 -    90097) | 844 Locations (IDs:    91000 -    92259)
  Risk of Rain 2              :  11 Items (IDs:    37001 -    37011) | 500 Locations (IDs:    37006 -    37505)
  Sonic Adventure 2 Battle    :  41 Items (IDs: 16711680 - 16711731) | 255 Locations (IDs: 16711680 - 16712451)
  Starcraft 2 Wings of Liberty: 111 Items (IDs:     1000 -     1802) | 119 Locations (IDs:     1100 -     3805)
  Super Metroid               :  30 Items (IDs:    83000 -    83037) | 105 Locations (IDs:    82000 -    82260)
  Super Mario 64              :  18 Items (IDs:  3626000 -  3626214) | 135 Locations (IDs:  3626000 -  3626214)
  SMZ3                        : 151 Items (IDs:    84000 -    84223) | 316 Locations (IDs:    85000 -    85510)
  Secret of Evermore          : 156 Items (IDs:    64000 -    64904) | 338 Locations (IDs:    64000 -    64385)
  Slay the Spire              :   4 Items (IDs:     8000 -     8003) |  31 Locations (IDs:    19001 -    22003)
  Subnautica                  :  81 Items (IDs:    35000 -    35080) | 181 Locations (IDs:    33000 -    34049)
  Timespinner                 : 181 Items (IDs:  1337000 -  1337249) | 212 Locations (IDs:  1337000 -  1337249)
  VVVVVV                      :  20 Items (IDs:  2515000 -  2515019) |  20 Locations (IDs:  2515000 -  2515019)
  The Witness                 : 185 Items (IDs:   158000 -   159987) | 585 Locations (IDs:   158000 -   158800)

Creating World.
Creating Items.
Calculating Access Rules.
Running Item Plando
Running Pre Main Fill.
Filling the world with 199 items.
Balancing multiworld progression for 2 Players.
Beginning output...
Could not access required locations for accessibility check. Missing: {IDLE for at least 50 minutes 0 seconds (JarnoPudle), IDLE for at least 26 minutes 30 seconds (JarnoPudle), IDLE for at least 29 minutes 0 seconds (JarnoPudle), IDLE for at least 45 minutes 30 seconds (JarnoPudle), IDLE for at least 35 minutes 0 seconds (JarnoPudle), Energy Tank, Waterway (SMJarno), IDLE for at least 28 minutes 30 seconds (JarnoPudle), Reserve Tank, Wrecked Ship (SMJarno), Missile (green Maridia shinespark) (SMJarno), IDLE for at least 45 minutes 0 seconds (JarnoPudle), IDLE for at least 32 minutes 30 seconds (JarnoPudle), IDLE for at least 34 minutes 0 seconds (JarnoPudle), IDLE for at least 38 minutes 0 seconds (JarnoPudle), IDLE for at least 36 minutes 30 seconds (JarnoPudle), IDLE for at least 35 minutes 30 seconds (JarnoPudle), Super Missile (pink Maridia) (SMJarno), IDLE for at least 48 minutes 0 seconds (JarnoPudle), IDLE for at least 32 minutes 0 seconds (JarnoPudle), IDLE for at least 44 minutes 30 seconds (JarnoPudle)}
Location Accessibility requirements not fulfilled.
Generating output files (2/2).
Calculating playthrough.
Uncaught exception
Traceback (most recent call last):
  File "T:\Git\Archipelago\Generate.py", line 737, in <module>
    main()
  File "T:\Git\Archipelago\Generate.py", line 270, in main
    callback(erargs, seed)
  File "T:\Git\Archipelago\Main.py", line 420, in main
    create_playthrough(world)
  File "T:\Git\Archipelago\Main.py", line 466, in create_playthrough
    raise RuntimeError(f'Not all progression items reachable ({sphere_candidates}). '
RuntimeError: Not all progression items reachable ({IDLE for at least 50 minutes 0 seconds (JarnoPudle), IDLE for at least 29 minutes 0 seconds (JarnoPudle), IDLE for at least 45 minutes 30 seconds (JarnoPudle), Missile (green Maridia shinespark) (SMJarno), IDLE for at least 45 minutes 0 seconds (JarnoPudle), IDLE for at least 34 minutes 0 seconds (JarnoPudle), IDLE for at least 38 minutes 0 seconds (JarnoPudle), IDLE for at least 35 minutes 30 seconds (JarnoPudle), Super Missile (pink Maridia) (SMJarno), IDLE for at least 48 minutes 0 seconds (JarnoPudle), IDLE for at least 44 minutes 30 seconds (JarnoPudle), IDLE for at least 26 minutes 30 seconds (JarnoPudle), IDLE for at least 35 minutes 0 seconds (JarnoPudle), Energy Tank, Waterway (SMJarno), IDLE for at least 28 minutes 30 seconds (JarnoPudle), Reserve Tank, Wrecked Ship (SMJarno), IDLE for at least 32 minutes 30 seconds (JarnoPudle), IDLE for at least 36 minutes 30 seconds (JarnoPudle), IDLE for at least 32 minutes 0 seconds (JarnoPudle)}). Something went terribly wrong here.
Traceback (most recent call last):
  File "T:\Git\Archipelago\Generate.py", line 737, in <module>
    main()
  File "T:\Git\Archipelago\Generate.py", line 270, in main
    callback(erargs, seed)
  File "T:\Git\Archipelago\Main.py", line 420, in main
    create_playthrough(world)
  File "T:\Git\Archipelago\Main.py", line 466, in create_playthrough
    raise RuntimeError(f'Not all progression items reachable ({sphere_candidates}). '
RuntimeError: Not all progression items reachable ({IDLE for at least 50 minutes 0 seconds (JarnoPudle), IDLE for at least 29 minutes 0 seconds (JarnoPudle), IDLE for at least 45 minutes 30 seconds (JarnoPudle), Missile (green Maridia shinespark) (SMJarno), IDLE for at least 45 minutes 0 seconds (JarnoPudle), IDLE for at least 34 minutes 0 seconds (JarnoPudle), IDLE for at least 38 minutes 0 seconds (JarnoPudle), IDLE for at least 35 minutes 30 seconds (JarnoPudle), Super Missile (pink Maridia) (SMJarno), IDLE for at least 48 minutes 0 seconds (JarnoPudle), IDLE for at least 44 minutes 30 seconds (JarnoPudle), IDLE for at least 26 minutes 30 seconds (JarnoPudle), IDLE for at least 35 minutes 0 seconds (JarnoPudle), Energy Tank, Waterway (SMJarno), IDLE for at least 28 minutes 30 seconds (JarnoPudle), Reserve Tank, Wrecked Ship (SMJarno), IDLE for at least 32 minutes 30 seconds (JarnoPudle), IDLE for at least 36 minutes 30 seconds (JarnoPudle), IDLE for at least 32 minutes 0 seconds (JarnoPudle)}). Something went terribly wrong here.
Press enter to close.

**Comment by Berserker66** [comment]
@espeon65536 something you want to look into? Let me know if not.

**Comment by Ijwu** [comment]
@espeon65536 let us know if not. :kappa:

**Comment by Jarno458** [comment]
Verified, still reproduceable on AP 0.3.4 with same yamls & seed

**Comment by Berserker66** [comment]
This should now be fixed in current /main

**Comment by Jarno458** [comment]
ill retest this, and close this issue if its ok

**Comment by Berserker66** [comment]
So?

**Comment by Jarno458** [comment]
Confirmed on 0.3.8 this issue nolonger exists
