### ISSUE TITLE
LTTP: GT Validation Chest should be added to the boss block list for collects

### ISSUE THREAD

**Issue by t3hf1gm3nt** [ArchipelagoMW/Archipelago#435]
Collecting the validation chest would skip the boss at the top of GT. This chest should be added to the boss block list

**Comment by Berserker66** [comment]
@CaitSith2

**Comment by CaitSith2** [comment]
If the spirit is having to kill the GT bosses, then the 3 chests in the basement that are Armos 2 locked,  as well as everything on top, which are Lanmolas 2 locked at minimum, with Validation being both Lanmolas 2 and Moldorm 2 locked.

**Comment by CaitSith2** [comment]
Actually, I don't think Moldorm 2 despwans with validation chest collected already, just that you can skip the boss or fight it still.  The boss dead flag is not written by the validation chest collection, but rather the heart container that never spawns in any of the GT boss rooms in GT state.

**Comment by CaitSith2** [comment]
And if KholdStare is at Moldorm 2, then you still need a fire rod or bombos for breaking its shell, even if you intend to skip the boss.

**Comment by t3hf1gm3nt** [comment]
Just did a test on my end. I was apparently misinformed. You are correct: collecting GT validation does NOT despawn the boss at Moldorm 2. So this issue is no longer needed for its original purpose. I'll close it and inform those on the discord who brought it up.
