### ISSUE TITLE
Factorio: Support increasing technology count to make check counts even between games

### ISSUE THREAD

**Issue by octylFractal** [ArchipelagoMW/Archipelago#4400]
### What feature would you like to see?

Currently, when playing with some games like Dark Souls 3, Factorio feels unbalanced as I can only get 27/179 checks, while my friend has 116/1190 after I've been waiting for a few hours. This leads to me waiting on them for my next science pack and being able to close the game instead of having to keep my factory running. It's also less likely that I find items for them, something that helps it feel like us playing the games together. 

I'd like to have the option to set the size of the location pool, and it's fine if this means there are duplicate items. Just having a more equal balance of number of locations that are for each other feels better to me.

**Comment by NewSoupVi** [comment]
~~Don't do it Zerk, don't cave into the check inflation~~

No but seriously, 1190 is unreasonable. That's something you can do in an async game that is supposed to take multiple weeks & where other people can submit multiple games. But in a live game, your friend should drastically change their approach to how they choose their options. That sounds like they cranked every setting to the absolute maximum

**Comment by NewSoupVi** [comment]
Update: Nevermind, it's 1190 by default. Now I'm wondering if there is a design issue with the DS3 randomizer, then.

**Comment by NewSoupVi** [comment]
In case anyone is curious, I decided to make a quick script that outputs the check counts on default settings per game

[default_checks.txt](https://github.com/user-attachments/files/18262706/default_checks.txt)

**Comment by Berserker66** [comment]
Factorio can have up to 400 additional locations if you  crank all Traps to max.

**Comment by octylFractal** [comment]
I disagree with that as a solution as I don't feel comfortable playing with traps, but if that's what it'll be then I won't push it anymore.
