### ISSUE TITLE
Item linked LTTP keys breaks multiworld tracker

### ISSUE THREAD

**Issue by Alchav** [ArchipelagoMW/Archipelago#481]
Item-linked keys in LTTP causes this error to occur any time the multiworld tracker page is accessed, making the page unloadable

`
  File "C:\src\Archipelago\WebHostLib\tracker.py", line 987, in getTracker
    player_small_key_locations[item_player].add(ids_small_key[item_id])
KeyError: 3
`

**Comment by alwaysintreble** [comment]
This issue didn't get tagged but it looks to already be resolved.

**Comment by Berserker66** [comment]
Should be fixed with https://github.com/ArchipelagoMW/Archipelago/commit/e13e7f286c013d4cd06e5664aa3adc8839988117



> This issue didn't get tagged but it looks to already be resolved.

It was not.
