### ISSUE TITLE
Add Sonic Adventure 2 Battle to the Network Graph

### ISSUE THREAD

**Issue by PoryGone** [ArchipelagoMW/Archipelago#540]
Sonic Adventure 2 Battle communicates to Archipelago via the APCpp Client.

**Comment by alwaysintreble** [comment]
is there a way to "automate" the network graph or do it in such a way that new worlds could easily add to it if they aren't familiar with mermaid?

**Comment by Ijwu** [comment]
Mermaid is necessary in order to update the graph. It is a fairly easy syntax, our document is just real large so it looks intimidating.
