### ISSUE TITLE
Issues should be opened for network graph additions.

### ISSUE THREAD

**Issue by Berserker66** [ArchipelagoMW/Archipelago#542]
![image](https://user-images.githubusercontent.com/3189725/169419187-b86316bb-f6b5-486d-9b42-619caf100363.png)

**Comment by Ijwu** [comment]
Not really funny. You could have spent the time making this making an actual useful one.

**Comment by Ijwu** [comment]
You know what's really bothersome about this now? I know there were TWO issues that needed to be created and only one of them is open and I have no clue what the other game was supposed to be. I've completely forgotten, as I said I would.
