### ISSUE TITLE
FFR AP participates do not receive MARK with FFR NOverworld preset settings

### ISSUE THREAD

**Issue by Pandatron76** [ArchipelagoMW/Archipelago#618]
Greetings all!

To begin, just wanted to give many thanks for the people that have contributed to AP. I have had loads of fun with it playing solo along with friends. During a recent play sessions with a few friends, we believe a potential bug was discovered as it relates to the FFR specific to AP. If this is not the correct medium to post about this, I will delete this message and migrate it to the appropriate location. Details of what we encountered below.

### Description 
When an AP game is generated via https://archipelago.gg/generate and at least one file in the compressed file (.zip in this case) contains a FFR yaml that is configured with the preset NOverworld along with a second yaml for a different game, the item that would replace the Canoe (MARK) does not convey from a remote world to the FFR world. The FFR player will obtain the Canoe but not MARK. The result of this is reduced access to locations to their own and potential items for others locked by MARK.

### Steps to Reproduce
 - Generate a rom and yaml file from https://4-4-0.finalfantasyrandomizer.com/ using the NOverworld present with AP enabled.
 - Create a yaml file for any game that is not FFR
 - Included both created yamls into a compressed file
 - Upload the file to https://archipelago.gg/generate with the !forfeit option enabled
 - Verify that the spoiler log has the Floater and Canoe in a/the non FFR world (this may take multiple generations)
 - Have both players load their world
 - Have the non FFR player use the !forfiet command

### Expected Result 
  FFR player obtains the MARK and SIGIL (and not Canoe or Floater as they are replaced respectively in NOverworld).

### Actual Result 
  FFR player obtains the SIGIL but not the MARK (or Canoe)

### Additional Notes 
 - This was initial discovered on a play session using FFR, SMZ3, ALttP and SM64
 - Was tested with FFR with SMZ3, FFR with SM64 and solo FFR and the result was reproduceable in all cases.
 - The FFR player has done practice sessions abstract of AP and could not reproduce this effect
 - For additional clarification, please feel free to reach out to Pandatron76#8419 on Discord and/or I can reply to messages on this thread.

**Comment by Ijwu** [comment]
@jtoyoda might have interest in this. I would attempt to replicate but cannot do so legally. :)

**Comment by jtoyoda** [comment]
@Pandatron76 thanks a lot for the bug report. We have never tested compatibility with NOverworld but it would be good to support it if it is possible
@mhn65536 is there anything special about the SIGIL and the MARK? I am pretty unfamiliar with NOverworld.

**Comment by Pandatron76** [comment]
@ljwu @jtoyoda

Thanks for the rapid response! The FFR specialist/enthusiast in our weekly group thoroughly enjoys the randomizer so when they heard it had been integrated in AP, they started trying out loads of options. So far this has been our only main hiccup! Will keep reporting as we find them.

My knowledge in programming is limited but the reference I found regarding MARK and SIGIL were in [Archipelago.cs](https://github.com/FiendsOfTheElements/FF1Randomizer/blob/9ed2a5aeae98d6411ecb6b17bcbea1ee710b1828/FF1Lib/Archipelago.cs#L285-L292) where it looks like it returns a text string (though not sure what its used for) and the opening text scrolls in [MetroidVaniaMaps.cs](https://github.com/FiendsOfTheElements/FF1Randomizer/blob/5e4cd1e330c69e62b3c83faff8888780f3f02a95/FF1Lib/MetroidVaniaMap.cs#L867-L890) where it looks like it changes the text if it noticed MARK or SIGIL. Hope it helps!

**Comment by wildham0** [comment]
I've put up a PR to fix this, https://github.com/ArchipelagoMW/Archipelago/pull/999
