### ISSUE TITLE
Port Options system from MultiWorld to AutoWorld

### ISSUE THREAD

**Issue by alwaysintreble** [ArchipelagoMW/Archipelago#839]
Rather than accessing options with a dict through `Autoworld.world.option_name[player]` the option classes can be moved to `Autoworld.options.option_name` or `Autoworld.options[option_name]` and the current `Autoworld.options` should be migrated to `Autoworld.option_definitions`.
Can potentially use a TypedDict to auto fill out `Autoworld.options` to mimic `Autoworld.option_definitions` and already be filled with default option values, then have the actual Options filled in during the generation parsing step and gain access to typing hints.

**Comment by alwaysintreble** [comment]
TypedDict doesn't work for auto generating dictionaries especially since it needs a custom method to be backwards compatible. Need to create a custom object (maybe dataclass?) That builds both the dictionaries of old behavior on the multiworld and new behavior on autoworld.

**Comment by BootsinSoots** [comment]
Is this what the #993 merge solved or is this unrelated?
