### ISSUE TITLE
Bring back Archipidle

### ISSUE THREAD

**Issue by Grrmo** [ArchipelagoMW/Archipelago#881]
Since it was the most stable game AP had ever to offer and it brilliantly helped flattening the BK curve according to our experience, please bring back ArchipIdle

**Comment by alwaysintreble** [comment]
It's still fully supported just hidden.

**Comment by Grrmo** [comment]
idle.multiworld.link doesn't show the client as it used to. I actually saw that it is still supported but we can't figure out how to get the client working

**Comment by Grrmo** [comment]
Addendum: The sites only content is a string "AginahBot"

**Comment by Grrmo** [comment]
And the yaml template is gone too :-/

**Comment by alwaysintreble** [comment]
site works fine for me. and settings page is still there too https://archipelago.gg/games/ArchipIDLE/player-settings

**Comment by Grrmo** [comment]
<img width="404" alt="image" src="https://user-images.githubusercontent.com/72080072/183741480-2201b016-4dcb-4a04-8260-d9004d06ea37.png">

No one of us gets anything different than a site with the text AginahBot. That's all :-/

**Comment by Grrmo** [comment]
<img width="381" alt="image" src="https://user-images.githubusercontent.com/72080072/183741816-977fc520-fe12-4d02-b81c-874b286809b1.png">
We don't get anything different than an empty site showing only the string AginahBot

**Comment by alwaysintreble** [comment]
it has to be `http://idle.multiworld.link/`
`https://idle.multiworld.link/` is not the same.

**Comment by Grrmo** [comment]
FInally sorted this one out since we used a browser that automatically makes https:// connections even when typing http://
Thank you so much so far, @alwaysintreble 

Still we believe that hiding this game on archipelago.gg and stripping its yaml from the player templates is not the way to go.
The Factorio randomizer also started as an April's Fools joke and is still there. ArchipIdle, in our opinion, is  a wonderful mechanism to put progress behind a timer.

So the request still stands: Please unhide it in the next release and provide the yaml with the release package

**Comment by KonoTyran** [comment]
Factorio is not an April fools joke, nor was it ever.  it was originally intended to just be some screenshots, but when working on it Berserker decided to make it real instead of joke.
on the contrary, Idle was always meant to be a joke and not taken seriously. it will be shown on the website during the month of April and that's it. it will never be a full year around thing. and as alwaysintreble said, its still accessible if you now its there, its just hidden.
