### ISSUE TITLE
Reimplement /received

### ISSUE THREAD

**Issue by black-sliver** [ArchipelagoMW/Archipelago#887]
When merging code for items_handling, `/received` for TextClient got broken, because "can receive, but can't send" is not a thing anymore.

Actual implementation does not require a server update. I misremembered. no_location/tags and items_handling are completely separate.

\
-- original text below --

Proposed solution 1:
* allow items_handling 0b011
* have TextClient check server_version and send ConnectUpdate to 0b011
* /received automagically works

Proposed solution 2:
* as above, but send the ConnectUpdate when /received is being used the first time

Proposed solution 3:
* implement server-side
* make berserker unhappy
* ?
* profit

**Comment by Berserker66** [comment]
One of these days we might implement an inventory tab and/or hint tab. At which point the client needs inventory anyway.

**Comment by Jarno458** [comment]
!vote 3

**Comment by Jarno458** [comment]
i dont think we should add more bloat to the server, if the client no matter what client it is wants to know about received items, it should just always connect with item handling, i dont like the suggestion to send a connect update for it, as changing the item handling wont re-send all previsuly send items right?
