### ISSUE TITLE
Progression Balancing issues

### ISSUE THREAD

**Issue by Grrmo** [ArchipelagoMW/Archipelago#900]
This post is based on the personal experience my cloud had when playing Archipelago seeds. For us as non - programmers it is quite impossible to come up with some kind of proof.

When progression balancing could either be turned on or off, in nearly all seeds we played, a moon pearl for ALttP players would kind of always appear in sphere 4 the latest.

When the progression balancing system changed, there were some discussions around it and one of our members asked about it in the discord and got the response that setting progression balancing to 50 would be equal to the old "on" setting.

Well it just isn't. In all the seeds we played we noticed shifts in hard progression items being placed waaaaay deepeer inside the multiworld than it used to.

The peak happened yesterday in a MW with ALttP and Timespinner where my mates moon pearl was placed in front of the emperors throne room which was literally the 9th last check before finishing the game and finishing my seed would have been quicker since I had go mode by then.

The moon pearl landed in sphere 11 out of 16:
https://archipelago.gg/dl_spoiler/-MUoOXddSROhiENePp1D-A

To us, this feels like the moon pearl has landed in the trash item pool and is used as a filling item when it is actually a hard access gate for this game and needs to be placed earlier. 

Summary:
In our experience, BK mode probability for ALttP has raised drastically since the change of the Progression Balancing system even though we have been assured that setting it to 50 is the same as the old setting "on", which is just not the truth at all.

Kindly advise how we can get the good experience back without downgrading to a version that has the old progression balancing system. Thank you

**Comment by Joethepic** [comment]
For lttp specifically I would recommend close to 70 if playing with other players especially if you have a lot of players

**Comment by nature1996** [comment]
Actually had a similar issue with The Witness, where black and White square where really late in the sphere, but gate more than half the game

**Comment by Fynxes** [comment]
Even after more games created and with different settings in the progression balancing between 50-70, there still seems to be inconsistencies. It would be incredibly nice if this can be checked and there is feedback on this.

Any other information may be helpful as well.

**Comment by Berserker66** [comment]
The new algorithm is doing more actual balancing between players, it's more *relative*. It looks at the player who post-randomization unlocks locations the faster by % and catches progression balanced players up to that speed in measure of % spheres cleared based on the % speed you set as progression balancing value in your settings.

As a result, if the result is a long multiworld to begin with, not much balancing will occur now, where it used to just move a bunch of stuff early without really looking at any comparison between players.

With questions like "which setting to get the old behaviour back" being impossible to answer, as that behaviour does not exist anymore. So whoever told you that 50 number was just guessing something.

That said, community reception of the new algorithm was not that great, so more tweaking/changing could be a good idea. Sure one can't please everyone, but one can please the majority.

**Comment by Grrmo** [comment]
It's unsatisfying that the issue is closed when the problem still persists even with progression balancing > 70 :-(
