### ISSUE TITLE
Subnautica: X-coord sign flipped for 'Degasi Seabase - Jellyshroom Cave - Outside PDA'

### ISSUE THREAD

**Issue by oneup40** [ArchipelagoMW/Archipelago#911]
'Degasi Seabase - Jellyshroom Cave - Outside PDA' is listed as having a position of `{'x': -83.2, 'y': -276.4, 'z': -345.5}`. I believe the X-coord got flipped though and should be +83.2

Attached screenshot shows what I believe to be that PDA at +83.2.
![image](https://user-images.githubusercontent.com/7097256/184547102-f614b51d-cb4d-4fbe-9e40-914daa864d75.png)

{x: -83.2, z: -345.5} seems to be outside the boundaries of Jellyshroom Cave.

In its current state, this also makes the check inaccessible since there's no way I can find to access those coordinates at that depth, potentially causing a broken seed if progression is placed there (thankfully the seed I was playing had junk there).

**Comment by Berserker66** [comment]
correct, fixing.
