### ISSUE TITLE
Subnautica: Laser cutter isn't needed for 'Grassy Plateaus West Wreck - Beam PDA'

### ISSUE THREAD

**Issue by oneup40** [ArchipelagoMW/Archipelago#913]
Right now, Locations.py lists 'Grassy Plateaus West Wreck - Beam PDA' as `'need_laser_cutter': True`; however, it isn't needed. Enter the wreck and find your way to the ventilation shaft under the stairs. Follow it until it opens up into the room that contains the Data Terminal. From this big room, there's a second ventilation shaft connected that takes you to the room with the Beam PDA.

**Comment by Berserker66** [comment]
Yep, found a path with just welder
