### ISSUE TITLE
Alttp: assert failures in fill_restrictive

### ISSUE THREAD

**Issue by black-sliver** [ArchipelagoMW/Archipelago#924]
The following locations (maybe more) have rules that depend on state:
- Turtle Rock - Big Key Chest
- Palace of Darkness - Harmless Hellway
- Palace of Darkness - Big Key Chest
- GT - Map Chest iirc

When filling in `fill_restrictive` we check with `maximum_exploration_state` but in `push_item` we assert with `self.state`, which seems to be different and fail the assertion. This accounts for quite a few generation failures in my random-yaml testing, so this should probably be fixed.
Ping me on discord if you need a reproducer, but I'm pretty sure the difference in state is what makes it crash.

**Comment by Berserker66** [comment]
@espeon65536

**Comment by Berserker66** [comment]
presumed fixed with https://github.com/ArchipelagoMW/Archipelago/pull/1702
