### ISSUE TITLE
Ocarina of Time Triforce Hunt Goal: Oversight of secondary goal logic

### ISSUE THREAD

**Issue by DJChupa13** [ArchipelagoMW/Archipelago#948]
In Ocarina of Time, there appears to be an oversight involving Triforce Hunt.  If **triforce_hunt** is set to _true_, and **shuffle_ganon_bosskey** is set to _remove_, It is possible to simply defeat Ganon to trigger the goal, even if the required amount of Triforce pieces haven't been obtained.

I assume what is happening is that the Ganondoor which is typically locked regardless of the goal is being mistakenly lifted when shuffle_ganon_bosskey set to remove.  Keeping the door locked is the safeguard to prevent Triforce Hunt seeds from killing Ganon to GG.  I think the intention was to ignore the value and remove the key as well as keeping the door locked.

That being said, it isn't exactly clear whether or not Triforce Hunt was ever intended to be the _only_ goal when turned on, so this is up to interpretation.  I referenced the template YAML, which reads: _Gather pieces of the Triforce scattered around the world to complete the game._  It does not specifically exclude defeating Ganon as a secondary goal.

**Comment by t3hf1gm3nt** [comment]
@espeon65536
